/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JinsiInavyofanyaKaziRouteImport } from './routes/jinsi-inavyofanya-kazi'
import { Route as MapatoRouteImport } from './routes/mapato'
import { Route as UsalamaRouteImport } from './routes/usalama'
import { Route as WanafunziIndexRouteImport } from './routes/wanafunzi.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JinsiInavyofanyaKaziRoute = JinsiInavyofanyaKaziRouteImport.update({
  id: '/jinsi-inavyofanya-kazi',
  path: '/jinsi-inavyofanya-kazi',
  getParentRoute: () => rootRouteImport,
} as any)
const MapatoRoute = MapatoRouteImport.update({
  id: '/mapato',
  path: '/mapato',
  getParentRoute: () => rootRouteImport,
} as any)
const UsalamaRoute = UsalamaRouteImport.update({
  id: '/usalama',
  path: '/usalama',
  getParentRoute: () => rootRouteImport,
} as any)
const WanafunziIndexRoute = WanafunziIndexRouteImport.update({
  id: '/wanafunzi/',
  path: '/wanafunzi/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jinsi-inavyofanya-kazi': typeof JinsiInavyofanyaKaziRoute
  '/mapato': typeof MapatoRoute
  '/usalama': typeof UsalamaRoute
  '/wanafunzi/': typeof WanafunziIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jinsi-inavyofanya-kazi': typeof JinsiInavyofanyaKaziRoute
  '/mapato': typeof MapatoRoute
  '/usalama': typeof UsalamaRoute
  '/wanafunzi': typeof WanafunziIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jinsi-inavyofanya-kazi': typeof JinsiInavyofanyaKaziRoute
  '/mapato': typeof MapatoRoute
  '/usalama': typeof UsalamaRoute
  '/wanafunzi/': typeof WanafunziIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/jinsi-inavyofanya-kazi' | '/mapato' | '/usalama' | '/wanafunzi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jinsi-inavyofanya-kazi' | '/mapato' | '/usalama' | '/wanafunzi'
  id:
    | '__root__'
    | '/'
    | '/jinsi-inavyofanya-kazi'
    | '/mapato'
    | '/usalama'
    | '/wanafunzi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JinsiInavyofanyaKaziRoute: typeof JinsiInavyofanyaKaziRoute
  MapatoRoute: typeof MapatoRoute
  UsalamaRoute: typeof UsalamaRoute
  WanafunziIndexRoute: typeof WanafunziIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinsi-inavyofanya-kazi': {
      id: '/jinsi-inavyofanya-kazi'
      path: '/jinsi-inavyofanya-kazi'
      fullPath: '/jinsi-inavyofanya-kazi'
      preLoaderRoute: typeof JinsiInavyofanyaKaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapato': {
      id: '/mapato'
      path: '/mapato'
      fullPath: '/mapato'
      preLoaderRoute: typeof MapatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usalama': {
      id: '/usalama'
      path: '/usalama'
      fullPath: '/usalama'
      preLoaderRoute: typeof UsalamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanafunzi/': {
      id: '/wanafunzi/'
      path: '/wanafunzi'
      fullPath: '/wanafunzi/'
      preLoaderRoute: typeof WanafunziIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JinsiInavyofanyaKaziRoute: JinsiInavyofanyaKaziRoute,
  MapatoRoute: MapatoRoute,
  UsalamaRoute: UsalamaRoute,
  WanafunziIndexRoute: WanafunziIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
